/**
 * Structural tests for parseCourse (UG and GS variants).
 *
 * Note: serialized_course_ug.json was generated by the Python crawler
 * aggregating multiple pages; course_ug_1.html is a single page of results.
 * They are not byte-for-byte comparable, so we test structural correctness
 * rather than full parity.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { parseCourse } from "../src/parsers/course.js";
import type { CoursePageResult } from "../src/types.js";

const FIXTURES = join(import.meta.dirname, "fixtures");

function readHtml(name: string) {
  return readFileSync(join(FIXTURES, name), "utf8");
}

function readJson<T>(name: string): T {
  return JSON.parse(readFileSync(join(FIXTURES, name), "utf8")) as T;
}

describe("parseCourse — course_ug_1 fixture", () => {
  const result = parseCourse(readHtml("course_ug_1.html"), "24251");
  const serialized = readJson<CoursePageResult>("serialized_course_ug.json");

  it("returns a non-empty entry list", () => {
    expect(result.list.length).toBeGreaterThan(0);
  });

  it("pagination fields match the fixture (page_no, page_size, total)", () => {
    expect(result.page_no).toBe(serialized.page_no);
    expect(result.page_size).toBe(serialized.page_size);
    expect(result.total).toBe(serialized.total);
  });

  it("every entry has required string fields", () => {
    for (const entry of result.list) {
      expect(typeof entry.lession_id).toBe("string");
      expect(typeof entry.semester).toBe("string");
      expect(typeof entry.name).toBe("string");
    }
  });

  it("credit is a number for every entry", () => {
    for (const entry of result.list) {
      if (entry.credit !== null) expect(typeof entry.credit).toBe("number");
    }
  });

  it("teacher is always an array of strings", () => {
    for (const entry of result.list) {
      expect(Array.isArray(entry.teacher)).toBe(true);
      for (const t of entry.teacher) expect(typeof t).toBe("string");
    }
  });

  it("course_type and teaching_class are arrays", () => {
    for (const entry of result.list) {
      expect(Array.isArray(entry.course_type)).toBe(true);
      expect(Array.isArray(entry.teaching_class)).toBe(true);
    }
  });

  it("has_syllabus is boolean or null", () => {
    for (const entry of result.list) {
      if (entry.has_syllabus !== null) expect(typeof entry.has_syllabus).toBe("boolean");
    }
  });
});

describe("parseCourse — course_gs_1 fixture (smoke)", () => {
  const result = parseCourse(readHtml("course_gs_1.html"), "24251");

  it("returns a non-empty entry list", () => {
    expect(result.list.length).toBeGreaterThan(0);
  });

  it("every entry has lession_id, semester, name", () => {
    for (const entry of result.list) {
      expect(typeof entry.lession_id).toBe("string");
      expect(entry.semester).toBe("24251");
      expect(typeof entry.name).toBe("string");
    }
  });
});
